const $=id=>document.getElementById(id);
const state={port:null,reader:null,connected:false,demoTimer:null,targets:[],rawCount:0,stableCount:0,countHistory:[],lastTargetAt:0,lastPresenceAt:0,heart:null,breath:null,distance:null,lux:null,history:[],frames:0,startedAt:performance.now()};
const radarCanvas=$('radarCanvas'),trendCanvas=$('trendCanvas'),radarCtx=radarCanvas.getContext('2d'),trendCtx=trendCanvas.getContext('2d');

function fitCanvas(canvas,ctx){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),width=Math.max(1,Math.round(rect.width*dpr)),height=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;ctx.setTransform(dpr,0,0,dpr,0,0)}return rect}

function drawRadar(){const{width:w,height:h}=fitCanvas(radarCanvas,radarCtx);radarCtx.clearRect(0,0,w,h);const cx=w/2,cy=h*.94,r=Math.min(w*.48,h*.88),g=radarCtx.createRadialGradient(cx,cy,0,cx,cy,r);g.addColorStop(0,'rgba(116,240,195,.08)');g.addColorStop(1,'rgba(116,240,195,0)');radarCtx.fillStyle=g;radarCtx.beginPath();radarCtx.moveTo(cx,cy);radarCtx.arc(cx,cy,r,Math.PI*7/6,Math.PI*11/6);radarCtx.closePath();radarCtx.fill();radarCtx.lineWidth=1;for(let m=1;m<=5;m++){radarCtx.strokeStyle=m===5?'rgba(116,240,195,.20)':'rgba(137,211,194,.10)';radarCtx.setLineDash(m===5?[]:[3,6]);radarCtx.beginPath();radarCtx.arc(cx,cy,r*m/5,Math.PI*7/6,Math.PI*11/6);radarCtx.stroke()}radarCtx.setLineDash([]);[-60,-30,0,30,60].forEach(deg=>{const a=(deg-90)*Math.PI/180;radarCtx.strokeStyle=deg===0?'rgba(116,240,195,.18)':'rgba(137,211,194,.08)';radarCtx.beginPath();radarCtx.moveTo(cx,cy);radarCtx.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);radarCtx.stroke()});const angle=((performance.now()/30)%120-150)*Math.PI/180,sg=radarCtx.createLinearGradient(cx,cy,cx+Math.cos(angle)*r,cy+Math.sin(angle)*r);sg.addColorStop(0,'rgba(116,240,195,0)');sg.addColorStop(1,'rgba(116,240,195,.55)');radarCtx.strokeStyle=sg;radarCtx.lineWidth=1.5;radarCtx.beginPath();radarCtx.moveTo(cx,cy);radarCtx.lineTo(cx+Math.cos(angle)*r,cy+Math.sin(angle)*r);radarCtx.stroke();radarCtx.fillStyle='#74f0c3';radarCtx.shadowColor='#74f0c3';radarCtx.shadowBlur=14;radarCtx.beginPath();radarCtx.arc(cx,cy,4,0,Math.PI*2);radarCtx.fill();radarCtx.shadowBlur=0;state.targets.forEach((target,i)=>{const x=cx+(Number(target.x_m)/5)*r,y=cy-(Number(target.y_m)/5)*r,halo=17+Math.sin(performance.now()/350+i)*3;radarCtx.fillStyle='rgba(116,240,195,.08)';radarCtx.beginPath();radarCtx.arc(x,y,halo,0,Math.PI*2);radarCtx.fill();radarCtx.fillStyle='#74f0c3';radarCtx.shadowColor='#74f0c3';radarCtx.shadowBlur=17;radarCtx.beginPath();radarCtx.arc(x,y,6,0,Math.PI*2);radarCtx.fill();radarCtx.shadowBlur=0;radarCtx.fillStyle='#dff9f0';radarCtx.font='600 10px system-ui';radarCtx.fillText(`T${i+1}`,x+12,y-8);radarCtx.fillStyle='rgba(190,218,211,.65)';radarCtx.font='9px system-ui';radarCtx.fillText(`${Math.hypot(target.x_m,target.y_m).toFixed(2)} m`,x+12,y+5)});requestAnimationFrame(drawRadar)}

function drawTrend(){const{width:w,height:h}=fitCanvas(trendCanvas,trendCtx);trendCtx.clearRect(0,0,w,h);const p={l:36,r:16,t:16,b:25},iw=w-p.l-p.r,ih=h-p.t-p.b;trendCtx.font='9px system-ui';trendCtx.textAlign='right';[0,30,60,90,120].forEach(v=>{const y=p.t+ih-v/120*ih;trendCtx.strokeStyle='rgba(137,211,194,.08)';trendCtx.beginPath();trendCtx.moveTo(p.l,y);trendCtx.lineTo(w-p.r,y);trendCtx.stroke();trendCtx.fillStyle='rgba(140,170,164,.5)';trendCtx.fillText(v,p.l-9,y+3)});function line(key,color){const values=state.history.filter(x=>Number.isFinite(x[key]));if(values.length<2)return;const now=Date.now();trendCtx.strokeStyle=color;trendCtx.lineWidth=2;trendCtx.shadowColor=color;trendCtx.shadowBlur=7;trendCtx.beginPath();values.forEach((x,i)=>{const px=p.l+Math.max(0,1-(now-x.time)/60000)*iw,py=p.t+ih-Math.min(120,Math.max(0,x[key]))/120*ih;i?trendCtx.lineTo(px,py):trendCtx.moveTo(px,py)});trendCtx.stroke();trendCtx.shadowBlur=0}line('heart','#ff7a7f');line('breath','#64d9f2');trendCtx.fillStyle='rgba(140,170,164,.5)';trendCtx.textAlign='center';trendCtx.fillText('Last 60 seconds',p.l+iw/2,h-6)}

function setConnection(ok,text){state.connected=ok;$('connectionPill').classList.toggle('connected',ok);$('connectionText').textContent=text;$('connectButton').textContent=ok&&!state.demoTimer?'Disconnect Sensor':'Connect Sensor'}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),5000)}
function updateStableCount(count){state.countHistory.push({count,time:Date.now()});state.countHistory=state.countHistory.filter(x=>Date.now()-x.time<2500);const f=new Map;state.countHistory.forEach(x=>f.set(x.count,(f.get(x.count)||0)+1));state.stableCount=[...f].sort((a,b)=>b[1]-a[1])[0]?.[0]??0}
function updatePresence(){const detected=(Date.now()-state.lastTargetAt<2600&&state.stableCount>0)||Date.now()-state.lastPresenceAt<2600;$('presenceCard').classList.toggle('active',detected);$('presenceText').textContent=detected?'Human Detected':'No Detection';$('presenceSubtext').textContent=detected?'Target present in the radar field of view':'No human target in the detection zone';$('stableCount').textContent=detected?(state.stableCount||1):0}
function updateTargets(items){$('targetList').innerHTML=items.length?items.map((t,i)=>`<div class="target-row"><div class="target-number">${i+1}</div><div class="target-main"><strong>Target ${i+1}</strong><span>X ${Number(t.x_m).toFixed(2)} m · Y ${Number(t.y_m).toFixed(2)} m</span></div><div class="target-speed">${Number(t.speed_cm_s||0).toFixed(1)} cm/s<span>cluster ${t.cluster_index??'--'}</span></div></div>`).join(''):'<div class="target-placeholder">No stable target coordinates</div>'}
const valid=(v,min,max)=>Number.isFinite(v)&&v>=min&&v<=max;
function refresh(){ $('heartValue').textContent=valid(state.heart,35,220)?Math.round(state.heart):'--';$('breathValue').textContent=valid(state.breath,4,60)?Math.round(state.breath):'--';$('distanceValue').textContent=Number.isFinite(state.distance)&&state.distance>0?state.distance.toFixed(1):'--';$('lightValue').textContent=Number.isFinite(state.lux)?Math.round(state.lux):'--';$('heartState').textContent=valid(state.heart,35,220)?'Current algorithm output':'Waiting for a stable reading';$('breathState').textContent=valid(state.breath,4,60)?'Current algorithm output':'Remain still for about 1 minute';$('rawCount').textContent=state.rawCount;$('radarEmpty').classList.toggle('hidden',state.targets.length>0);updatePresence()}

function handleEvent(e){state.frames++;$('lastFrameText').textContent=`Last frame ${new Date().toLocaleTimeString('en-GB',{hour12:false})}`;switch(e.kind){case'presence':if(e.detected)state.lastPresenceAt=Date.now();break;case'targets':state.targets=Array.isArray(e.items)?e.items:[];state.rawCount=Number(e.count)||state.targets.length;state.lastTargetAt=Date.now();updateStableCount(state.rawCount);updateTargets(state.targets);break;case'heart_rate':state.heart=Number(e.bpm);break;case'breath_rate':state.breath=Number(e.bpm);break;case'distance':state.distance=Number(e.cm);break;case'illuminance':state.lux=Number(e.lux);break}if(e.kind==='heart_rate'||e.kind==='breath_rate'){state.history.push({time:Date.now(),heart:state.heart,breath:state.breath});state.history=state.history.filter(x=>Date.now()-x.time<60000);drawTrend()}refresh()}

async function connectSerial(){if(state.connected&&!state.demoTimer)return disconnect();stopDemo();if(!('serial'in navigator)){toast('Web Serial is not supported in this browser. Use Microsoft Edge or Google Chrome and open the page from localhost.');return}try{state.port=await navigator.serial.requestPort();await state.port.open({baudRate:115200});setConnection(true,'Sensor connected · 115200');readLoop()}catch(e){if(e.name!=='NotFoundError')toast(`Connection failed: ${e.message}`)}}
async function readLoop(){const decoder=new TextDecoderStream(),closed=state.port.readable.pipeTo(decoder.writable).catch(()=>{});state.reader=decoder.readable.getReader();let buffer='';try{while(state.connected){const{value,done}=await state.reader.read();if(done)break;buffer+=value;const lines=buffer.split(/\r?\n/);buffer=lines.pop()||'';for(const line of lines){if(!line.trim().startsWith('{'))continue;try{handleEvent(JSON.parse(line))}catch{}}}}catch(e){if(state.connected)toast(`Serial reading stopped: ${e.message}`)}finally{state.reader?.releaseLock();await closed}}
async function disconnect(){setConnection(false,'Waiting for connection');try{await state.reader?.cancel()}catch{}try{await state.port?.close()}catch{}state.reader=null;state.port=null}
function startDemo(){if(state.demoTimer){stopDemo();return}if(state.connected)disconnect();setConnection(true,'Simulated data · DEMO');$('demoButton').textContent='Stop Demo';const start=performance.now();state.demoTimer=setInterval(()=>{const t=(performance.now()-start)/1000,x1=-.34+Math.sin(t/3)*.13,y1=1.18+Math.cos(t/4)*.07,x2=.72+Math.sin(t/4.5)*.18,y2=2.25+Math.cos(t/5)*.12;handleEvent({kind:'targets',count:2,items:[{x_m:x1,y_m:y1,speed_cm_s:Math.abs(Math.cos(t/3))*2.3,cluster_index:0},{x_m:x2,y_m:y2,speed_cm_s:Math.abs(Math.sin(t/4.5))*4.1,cluster_index:1}]});handleEvent({kind:'presence',detected:true});handleEvent({kind:'distance',cm:Math.hypot(x1,y1)*100});handleEvent({kind:'heart_rate',bpm:76+Math.sin(t/5)*3+Math.sin(t*1.7)});handleEvent({kind:'breath_rate',bpm:15+Math.sin(t/7)*1.5});handleEvent({kind:'illuminance',lux:138+Math.sin(t/8)*12})},650)}
function stopDemo(){if(!state.demoTimer)return;clearInterval(state.demoTimer);state.demoTimer=null;$('demoButton').textContent='Demo Mode';setConnection(false,'Waiting for connection')}
$('connectButton').addEventListener('click',connectSerial);$('demoButton').addEventListener('click',startDemo);addEventListener('resize',drawTrend);setInterval(()=>{updatePresence();const sec=Math.max(1,(performance.now()-state.startedAt)/1000);$('frameRate').textContent=`${state.frames} frames · ${(state.frames/sec).toFixed(1)} fps avg`},500);drawRadar();drawTrend();
